### ISSUE TITLE
When env is declared in wrong way, highway will hang without indicating error.

### ISSUE THREAD

**Issue by Siemian** [netguru/highway#7] opened 2020-07-17 19:14 UTC
**AS IS:**
Declaring step like this:
```
bootstrap:
    default:
        - sh:
            command: "echo $VARIABLE"
```
instead of 
```
bootstrap:
    default:
        - sh:
            command: "echo $(VARIABLE)"
```
will cause Highway to hang on:
```
--- Compiling the configuration file...
```
**TO BE:**
Highway should throw error

**Comment by piotr-sekara** [comment] 2020-10-29 10:59
@Siemian Could you provide more information about this bug? I can't reproduce this problem. Maybe you have an Highwayfile on which problem occurred?

**Comment by Siemian** [comment] 2020-10-29 11:04
Unfortunately what's in issue description is all I got.

**Comment by piotr-sekara** [comment] 2020-10-29 11:11
I will close this issue for now as we're not able to reproduce it anymore.

**Closed by piotr-sekara** 2020-10-29 11:11 UTC
Labels: bug
